name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['8.0.x']

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Install WSL (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        # Install WSL using wsl --install command
        wsl --install --no-distribution
        
        # Install Debian specifically
        wsl --install -d Debian
        
        # Ensure WSL2 is default
        wsl --set-default-version 2
        
        # Wait for WSL to be ready and verify
        Start-Sleep -Seconds 30
        wsl -- uname -a
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Pack
      run: dotnet pack --configuration Release BashSharp/BashSharp.csproj
    
    - name: Push to NuGet
      run: dotnet nuget push "BashSharp/bin/Release/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json 